name: Build Swipto Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Prepare main.py
      run: |
        cp swipto_app.py main.py

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Flet Build Tools
      run: |
        python -m pip install --upgrade pip
        pip install "flet[all]"
        pip install -r requirements.txt

    - name: Build Android APK
      run: |
        flet build apk -v

    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Swipto-Narsampet-APK
        path: build/apk/*.apk
